apiVersion: cache.gcp.crossplane.io/v1beta1
kind: CloudMemorystoreInstanceClass
metadata:
  name: gcp-redis-standard
  labels:
    app: doc
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  forProvider:
    tier: BASIC
    region: us-central1
    locationId: us-central1-c
    memorySizeGb: 1
  providerRef:
    name: gcp-provider
  reclaimPolicy: Delete