apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: doc-postgres
spec:
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: us-central1
    settings:
      tier: db-custom-1-3840
      dataDiskSizeGb: 10
      ipConfiguration:
        ipv4Enabled: false
        privateNetwork: "projects/${PROJECT_ID}/global/networks/default"
  writeConnectionSecretToRef:
    name: doc-db
    namespace: crdsdev
