apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc
  namespace: crdsdev
  labels:
    app: doc
spec:
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      containers:
        - name: doc
          image: crdsdev/doc:latest
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: doc-redis
                  key: endpoint
          ports:
            - containerPort: 5000
              name: doc
---
apiVersion: v1
kind: Service
metadata:
  name: doc
  namespace: crdsdev
  labels:
    app: doc
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: doc
  type: NodePort