apiVersion: cache.crossplane.io/v1alpha1
kind: RedisCluster
metadata:
  name: doc-redis
  namespace: crdsdev
spec:
  classSelector:
    matchLabels:
      app: doc
  writeConnectionSecretToRef:
    name: doc-redis
  engineVersion: "4.0"